name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decode google-services.json
      env:
        GS_SECRET: ${{ secrets.GS_SECRET }}
      run: echo $GS_SECRET > Pocketbook/app/google-services.json
      
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build 
      
    
    - name: Instrumented Tests
      uses: ReactiveCircus/android-emulator-runner@v2.12.0
      with:
        api-level: 30
        script: chmod +x gradlew && ./gradlew connectedCheck --stacktrace
