name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decode google-services.json
      env:
        GS_SECRET: ${{ secrets.GS_SECRET }}
      run: echo $GS_SECRET > app/google-services.json

    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build 

  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Decode google-services.json
      env:
        GS_SECRET: ${{ secrets.GS_SECRET }}
      run: echo $GS_SECRET > app/google-services.json

    - name: Unit Tests
      run: chmod +x gradlew && ./gradlew test 
      
  androidTest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Decode google-services.json
      env:
        GS_SECRET: ${{ secrets.GS_SECRET }}
      run: echo $GS_SECRET > app/google-services.json
    
    - name: Intent Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        script: chmod +x gradlew && ./gradlew connectedCheck --stacktrace
